### ISSUE TITLE
Container transactions issue

### ISSUE THREAD

**Issue by Mclarcj** [yitzy299/blocklogger#13]
When you fill a chest up with block's and break it you don't see who broke it just who added all the blocks which dosen't find out who stole what. (I apologise for spelling and grammar issues)

**Comment by yitzy299** [comment]
I believe this is intended behaviour - we can log inventory pickup eventually

**Comment by Mclarcj** [comment]
no as in it dosn't show the block break

**Comment by yitzy299** [comment]
I will have a look myself

**Comment by Mclarcj** [comment]
![bl data1](https://user-images.githubusercontent.com/73421864/99581814-29271000-29d9-11eb-847d-26fb2756c4d1.png)
![bl data2](https://user-images.githubusercontent.com/73421864/99581816-2a583d00-29d9-11eb-9ce5-914f042b8125.png)

**Comment by yitzy299** [comment]
This is an issue with the SQL, I will have a look now

**Comment by Mclarcj** [comment]
> This is an issue with the SQL, I will have a look now

any luck?

**Comment by yitzy299** [comment]
Yes, I believe this has been patched

**Comment by Mclarcj** [comment]
Ok I’ll check tomorrow
