### ISSUE TITLE
search limit

### ISSUE THREAD

**Issue by LOKIrc** [yitzy299/blocklogger#24]
this mod only provied at least 10 actions
how can I find actions which eariler than that 10 actions?
I try to open the file "blocklogger.bl" under the world folder,but I can't open it.
It look like in my picture
![截屏2021-02-26 下午7 49 04](https://user-images.githubusercontent.com/67812862/109296671-af21e500-786b-11eb-80b1-3837fed76f4d.png)

**Comment by yitzy299** [comment]
It's a database, you need a DB browser to read it. Blocklogger is no longer under active development, please see the new repo (where this has been implemented) at https://github.com/fabricservertools/deltalogger
