### ISSUE TITLE
Only 1 DB result returned when /bl is run

### ISSUE THREAD

**Issue by CookieJarApps** [yitzy299/blocklogger#7]
Every block destruction event should be printed for the coordinates

**Comment by yitzy299** [comment]
I’m aware, I’m currently fixing

**Comment by yitzy299** [comment]
Fixed in the latest commit

**Comment by CookieJarApps** [comment]
BTW if you copy and paste the commit number it links it: caccd38adc57d21ff7cf097aa7daadd3c5ecbb31
