### ISSUE TITLE
[Suggestion] A way to disable the "[BL] Saved data console message"

### ISSUE THREAD

**Issue by smallpepperz1** [yitzy299/blocklogger#8]
I'm one of those people that looks at their console to check up on stuff regularly, and in my short testing period, I noticed that every block break logs a `[14:12:22] [Server thread/INFO]: [STDOUT]: [BL] Saved data` message, and I think if this was disable-able in the configs, that would be nice.

**Comment by yitzy299** [comment]
Was fixed in comit 8482fd2
